export const GET_ALL_ROOMS = 'GET_ALL_ROOMS';
export const GET_FREE_ROOMS = 'GET_FREE_ROOMS';
export const GET_ONE_ROOM = 'GET_ONE_ROOM';
export const SET_ROOMS_LOADING = 'SET_ROOMS_LOADING';

export const GET_ALL_MEETINGS = 'GET_ALL_MEETINGS';
export const GET_CREATED_MEETINGS = 'GET_CREATED_MEETINGS';
export const GET_VISITED_MEETINGS = 'GET_VISITED_MEETINGS';
export const SET_MEETINGS_LOADING = 'SET_MEETINGS_LOADING';